services:
  tweedegolf_swiftmailer_logger.send_listener:
    class: TweedeGolf\SwiftmailerLoggerBundle\EventListener\SendListener
    arguments:
      - [@tweedegolf_swiftmailer_logger.entity_logger]

  tweedegolf_swiftmailer_logger.entity_logger:
    class:  TweedeGolf\SwiftmailerLoggerBundle\Logger\EntityLogger
    arguments:
      - @doctrine
