services:
  tweedegolf_swiftmailer_logger.send_listener:
    class: TweedeGolf\SwiftmailerLoggerBundle\EventListener\SendListener

  # loggers
  tweedegolf_swiftmailer_logger.entity_logger:
    class:  TweedeGolf\SwiftmailerLoggerBundle\Logger\EntityLogger
    arguments:
      - @doctrine

  tweedegolf_swiftmailer_logger.file_logger:
    class:  TweedeGolf\SwiftmailerLoggerBundle\Logger\FileLogger
    arguments:
      - @custom_logger

  # do this in extension?
  custom_logger:
    class: Symfony\Bridge\Monolog\Logger
    arguments: ['swiftmailer']
    calls:
        - [pushHandler, [@my_handler]]

  my_handler:
    class: Monolog\Handler\StreamHandler
    arguments: [%kernel.root_dir%/logs/swiftmailer.log]

