services:
  tweedegolf_swiftmailer_logger.send_listener:
    class: TweedeGolf\SwiftmailerLoggerBundle\EventListener\SendListener

  # loggers
  tweedegolf_swiftmailer_logger.entity_logger:
    class:  TweedeGolf\SwiftmailerLoggerBundle\Logger\EntityLogger
    arguments:
      - @doctrine

  tweedegolf_swiftmailer_logger.file_logger:
    class:  TweedeGolf\SwiftmailerLoggerBundle\Logger\FileLogger
    arguments:
      - @logger
    tags:
      - { name: monolog.logger}

